repos:
  # Basic Hooks for Code Hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace # Removes trailing whitespaces
        exclude: \.fcs$
      - id: end-of-file-fixer # Ensures files end with a newline
        exclude: \.fcs$
      - id: check-yaml # Validates YAML files
      - id: check-json # Validates JSON files
      - id: check-added-large-files # Warns about large files being committed
      - id: check-merge-conflict  # Prevents merge conflict markers in code

  # Automatic code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # isort for Import Sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"] # Ensures compatibility with Black

  # Flake8 for Linting
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=88", "--ignore=E501,W503,E203"]  # Match Black's line length


  # Codespell for Spell Checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell  # Corrects common typos in code and documentation
        args: ["--skip", "*.fcs"]

  # Pip-audit for Dependency Security
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit  # Checks for vulnerabilities in Python dependencies
